"""Typo fix

Revision ID: 26b5da6b38bc
Revises: 7ad282df807f
Create Date: 2022-07-23 20:04:32.531430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b5da6b38bc'
down_revision = '7ad282df807f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readers_books', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('readers_books', 'id')
    # ### end Alembic commands ###
