"""Added user role

Revision ID: 46318ae80f44
Revises: 612653d9f497
Create Date: 2022-07-28 16:35:51.225183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46318ae80f44'
down_revision = '612653d9f497'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'moderator', 'user', name='userrole'), server_default='user', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
