"""Initial

Revision ID: 4e458f000b25
Revises: dcc02326556a
Create Date: 2022-07-15 17:56:14.116685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e458f000b25'
down_revision = None
# 'dcc02326556a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
