"""Genre to False

Revision ID: 5cb92c2f92f0
Revises: d85cd8dbed0b
Create Date: 2022-07-23 22:04:46.215110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5cb92c2f92f0'
down_revision = 'd85cd8dbed0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'genre',
               existing_type=postgresql.ENUM('fiction', 'non_fiction', 'short_story', name='bookgenre'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'genre',
               existing_type=postgresql.ENUM('fiction', 'non_fiction', 'short_story', name='bookgenre'),
               nullable=True)
    # ### end Alembic commands ###
