"""v1

Revision ID: 603585c7dffe
Revises: 1639a26060fa
Create Date: 2022-07-15 17:51:41.645563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603585c7dffe'
down_revision = '1639a26060fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('pages', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'pages')
    # ### end Alembic commands ###
