"""v2

Revision ID: 8711d7e58d10
Revises: 603585c7dffe
Create Date: 2022-07-22 11:15:43.772372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8711d7e58d10'
down_revision = '603585c7dffe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first name', sa.String(), nullable=True),
    sa.Column('last name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readers')
    # ### end Alembic commands ###
