"""Updated readers fields

Revision ID: 8bc2302cc18f
Revises: bcae7f65bfbd
Create Date: 2022-07-23 19:15:30.633728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc2302cc18f'
down_revision = 'bcae7f65bfbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('reader_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_books_reader_id'), 'books', ['reader_id'], unique=False)
    op.create_foreign_key(None, 'books', 'readers', ['reader_id'], ['id'])
    op.add_column('readers', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('readers', sa.Column('last_name', sa.String(), nullable=True))
    op.drop_column('readers', 'last name')
    op.drop_column('readers', 'first name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readers', sa.Column('first name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('readers', sa.Column('last name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('readers', 'last_name')
    op.drop_column('readers', 'first_name')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_index(op.f('ix_books_reader_id'), table_name='books')
    op.drop_column('books', 'reader_id')
    # ### end Alembic commands ###
