"""Typo fix

Revision ID: a08dcf7b6dc1
Revises: 9af81b8c7161
Create Date: 2022-07-23 20:08:24.295976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a08dcf7b6dc1'
down_revision = '9af81b8c7161'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readers_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['reader_id'], ['readers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reader_books')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reader_books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reader_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='reader_books_book_id_fkey'),
    sa.ForeignKeyConstraint(['reader_id'], ['readers.id'], name='reader_books_reader_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reader_books_pkey')
    )
    op.drop_table('readers_books')
    # ### end Alembic commands ###
