"""Updated reader field in books

Revision ID: af8be60740ed
Revises: 88b1eef95a00
Create Date: 2022-07-23 19:23:40.393690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8be60740ed'
down_revision = '88b1eef95a00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'reader_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'reader_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
