"""Typo fix

Revision ID: ca7319ebaebf
Revises: 6357161e54e1
Create Date: 2022-07-23 20:01:42.280854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca7319ebaebf'
down_revision = '6357161e54e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
