"""Added user role

Revision ID: d1ab6591c4c5
Revises: 5cb92c2f92f0
Create Date: 2022-07-28 16:31:09.695312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ab6591c4c5'
down_revision = '5cb92c2f92f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    role = postgresql.ENUM('admin', 'moderator', 'user', name='role')
    users.create(op.get_bind())
    op.add_column('users', sa.Column('user_role', sa.Enum('admin', 'moderator', 'user', name='role'), server_default='user', nullable=False))
    # ### end Alembic commands ###
    op.execute("UPDATE users SET role = 'user'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_role')
    # ### end Alembic commands ###
