"""Added enum type

Revision ID: d85cd8dbed0b
Revises: cab663fcf76b
Create Date: 2022-07-23 21:52:57.718289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'd85cd8dbed0b'
down_revision = 'cab663fcf76b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bookgenre = postgresql.ENUM('fiction', 'non_fiction', 'short_story', name='bookgenre')
    bookgenre.create(op.get_bind())
    op.add_column('books', sa.Column('genre', sa.Enum('fiction', 'non_fiction', 'short_story', name='bookgenre'), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE books SET genre = 'fiction'")
    # op.alter_column('books', 'genre', nullable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'genre')
    # ### end Alembic commands ###
